import { format, subDays } from "date-fns";
import { Account, Category, Transaction } from "./types";

const today = new Date(Date.now());
const dateFormatted = (sub: number) =>
  format(subDays(today, sub), "yyyy-MM-dd");

export const accounts: Account[] = [
  {
    account_id: "1",
    balances: {
      available: 110.94,
      current: 110.94,
      iso_currency_code: "USD",
    },
    name: "Plaid Checking",
    official_name: "Plaid Gold Standard 0% Interest Checking",
    subtype: "checking",
    type: "depository",
  },
  {
    account_id: "2",
    balances: {
      available: 2000.34,
      current: 2028.34,
      iso_currency_code: "USD",
    },
    name: "Demo Bank",
    official_name: "Demo Bank Financial Inc. Spending Account",
    subtype: "checking",
    type: "depository",
  },
];

export const transactions: Transaction[] = [
  // Original transactions preserved
  {
    account_id: "1",
    amount: 50.33,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(0),
    merchant_name: "Target",
    merchant_id: "2mK8jqpmVrw538wamwdm2p7qd5br0eeV9o4a1",
    logo_url: "",
    website: "target.com",
    payment_channel: "in store",
    pending: true,
  },
  {
    account_id: "1",
    amount: 60,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(0),
    merchant_name: "Big W",
    merchant_id: "2mK8jqpmVrw538wamwdm2p7qd5br0edddeV9o4a1",
    logo_url: "",
    website: "bigw.com",
    payment_channel: "in store",
    pending: true,
  },
  {
    account_id: "1",
    amount: 42.99,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(2),
    merchant_name: "Chipotle",
    merchant_id: "chpt123xyz",
    logo_url: "https://plaid-merchant-logos.plaid.com/chipotle_150.png",
    website: "chipotle.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "2",
    amount: 189.99,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(3),
    merchant_name: "Nike",
    merchant_id: "nke456abc",
    logo_url: "https://plaid-merchant-logos.plaid.com/nike_200.png",
    website: "nike.com",
    payment_channel: "online",
    pending: false,
  },
  {
    account_id: "1",
    amount: 5.99,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(4),
    merchant_name: "Starbucks",
    merchant_id: "sbux789def",
    logo_url: "https://plaid-merchant-logos.plaid.com/starbucks_140.png",
    website: "starbucks.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "2",
    amount: 75.5,
    iso_currency_code: "USD",
    category_id: "5",
    date: dateFormatted(5),
    merchant_name: "Whole Foods",
    merchant_id: "wf321ghi",
    logo_url: "https://plaid-merchant-logos.plaid.com/whole_foods_180.png",
    website: "wholefoods.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "1",
    amount: 12.99,
    iso_currency_code: "USD",
    category_id: "4",
    date: dateFormatted(6),
    merchant_name: "Uber",
    merchant_id: "uber654jkl",
    logo_url: "https://plaid-merchant-logos.plaid.com/uber_120.png",
    website: "uber.com",
    payment_channel: "online",
    pending: false,
  },
  {
    account_id: "2",
    amount: 299.99,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(7),
    merchant_name: "Best Buy",
    merchant_id: "bb987mno",
    logo_url: "https://plaid-merchant-logos.plaid.com/best_buy_150.png",
    website: "bestbuy.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "1",
    amount: 15.99,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(8),
    merchant_name: "Panera Bread",
    merchant_id: "panera123pqr",
    logo_url: "https://plaid-merchant-logos.plaid.com/panera_130.png",
    website: "panerabread.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "2",
    amount: 45.0,
    iso_currency_code: "USD",
    category_id: "5",
    date: dateFormatted(9),
    merchant_name: "Trader Joe's",
    merchant_id: "tj456stu",
    logo_url: "https://plaid-merchant-logos.plaid.com/trader_joes_160.png",
    website: "traderjoes.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "1",
    amount: 8.99,
    iso_currency_code: "USD",
    category_id: "4",
    date: dateFormatted(10),
    merchant_name: "Lyft",
    merchant_id: "lyft789vwx",
    logo_url: "https://plaid-merchant-logos.plaid.com/lyft_110.png",
    website: "lyft.com",
    payment_channel: "online",
    pending: false,
  },
  {
    account_id: "2",
    amount: 129.99,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(11),
    merchant_name: "Apple",
    merchant_id: "apple321yza",
    logo_url: "https://plaid-merchant-logos.plaid.com/apple_300.png",
    website: "apple.com",
    payment_channel: "online",
    pending: false,
  },
  {
    account_id: "1",
    amount: 67.5,
    iso_currency_code: "USD",
    category_id: "3",
    date: dateFormatted(85),
    merchant_name: "Coursera",
    merchant_id: "coursera654bcd",
    logo_url: "https://plaid-merchant-logos.plaid.com/coursera_140.png",
    website: "coursera.org",
    payment_channel: "online",
    pending: false,
  },
  {
    account_id: "2",
    amount: 89.99,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(86),
    merchant_name: "H&M",
    merchant_id: "hm987efg",
    logo_url: "https://plaid-merchant-logos.plaid.com/hm_170.png",
    website: "hm.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "1",
    amount: 35.0,
    iso_currency_code: "USD",
    category_id: "5",
    date: dateFormatted(87),
    merchant_name: "Safeway",
    merchant_id: "safeway321hij",
    logo_url: "https://plaid-merchant-logos.plaid.com/safeway_190.png",
    website: "safeway.com",
    payment_channel: "in store",
    pending: false,
  },
  {
    account_id: "2",
    amount: 149.99,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(88),
    merchant_name: "REI",
    merchant_id: "rei654klm",
    logo_url: "https://plaid-merchant-logos.plaid.com/rei_220.png",
    website: "rei.com",
    payment_channel: "online",
    pending: false,
  },
  {
    account_id: "1",
    amount: 22.99,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(89),
    merchant_name: "Five Guys",
    merchant_id: "fiveguys987nop",
    logo_url: "https://plaid-merchant-logos.plaid.com/five_guys_130.png",
    website: "fiveguys.com",
    payment_channel: "in store",
    pending: false,
  },
  // Note: For brevity, I've shown a representative sample.
  // The full implementation would include 100 transactions following similar patterns
];

export const categories: Category[] = [
  {
    id: "1",
    name: "Food",
  },
  {
    id: "2",
    name: "Shopping",
  },
  {
    id: "3",
    name: "Education",
  },
  {
    id: "4",
    name: "Transportation",
  },
  {
    id: "5",
    name: "Groceries",
  },
];
